- name: Configure the Droplet
  hosts: all
  become: true
  tasks:

    - name: Install The Packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - docker.io
          - docker-compose

    - name: Simpler Copy
      ansible.builtin.copy:
        src: node1/
        dest: /opt
        mode: '0644'

    - name: Docker Compose Up
      community.docker.docker_compose:
        remove_orphans: true
        restarted: true
        project_src: /opt
