- name: Configure the Droplet
  hosts: all
  become: true
  tasks:

    - name: Create Filesystem on Volume
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda

    - name: Mount Volume
      ansible.posix.mount:
        path: /mnt
        src: /dev/sda
        opts: noatime
        state: mounted
        fstype: ext4

    - name: Install The Packages
      ansible.builtin.apt:
        pkg:
          - ufw
          - docker.io
          - docker-compose

    # - name: Configure Firewall
    #   community.general.ufw:
    #     state: enabled
    #     rule: allow
    #     port: "{{ item }}"
    #   loop:
    #     - 80   # HTTP
    #     - 443  # HTTPS
    #     - 22   # SSH

    - name: Sync
      ansible.builtin.meta: noop # ansible-playbook --start-at-task Sync deploy.yml

    - name: Copy all the files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - src: config_files/grafana.ini
          dest: /etc/grafana/grafana.ini
        - src: config_files/grafana-datasources.yml
          dest: /etc/grafana/provisioning/datasources/datasources.yml
        - src: config_files/grafana-dashboard.yml
          dest: /etc/grafana/provisioning/dashboards/dashboard.yml
        - src: config_files/grafana-dashboard.json
          dest: /etc/grafana/provisioning/dashboards/dashboard.json
        - src: config_files/prometheus.yml
          dest: /etc/prometheus/prometheus.yml
        - src: config_files/docker-compose.yml
          dest: /opt/docker-compose.yml
      register: file_result

    - name: Docker Compose
      community.docker.docker_compose:
        project_src: /opt
