- name: Configure the Droplet
  hosts: all
  become: true
  tasks:

    - name: Create Filesystem on Volume
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda

    - name: Mount Volume
      ansible.posix.mount:
        path: /mnt
        src: /dev/sda
        opts: noatime
        state: mounted
        fstype: ext4

    - name: Install The Packages
      ansible.builtin.apt:
        pkg:
          - ufw
          - docker.io
          - docker-compose

    - name: Configure Firewall
      community.general.ufw:
        state: enabled
        rule: allow
        port: "{{ item }}"
      loop:
        - 80   # HTTP
        - 443  # HTTPS
        - 22   # SSH
        - 9090 # Prometheus
        - 3000 # Grafana

    - name: Simpler Copy
      ansible.builtin.copy:
        src: config_files/
        dest: /opt
        mode: '0644'

    - name: Docker Compose
      community.docker.docker_compose:
        project_src: /opt
