---
- name: My first play
  hosts: digitalocean
  tasks:
   - name: Ping my hosts
     ping:
   - name: Update and install vim
     import_tasks: tasks/essential.yaml
   - name: Print message
     debug:
      msg: Hello world
