---
- name: My first play
  hosts: digitalocean
  tasks:
   - name: Ping my hosts
     ping:
   - name: Update packages
     apt:
      update_cache: true
      upgrade: true
   - name: Install essential packages
     package:
      name:
       - vim
      state: latest
   - name: Print message
     debug:
      msg: Hello world
