# https://docs.docker.com/compose/compose-file/compose-file-v3
version: '3'

networks:
  default:
    internal: true
  proxy:
    internal: false

x-monitoring_defaults: &monitoring_defaults
  restart: always
  labels:
    - "owner=monitoring"

x-application_defaults: &application_defaults
  restart: on-failure
  labels:
    - "owner=applications"

services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.8.2
    restart: always
    container_name: haproxy
    labels:
      - "owner=proxy"
    volumes:
      - /opt/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /root/haproxy.pem:/haproxy.pem # scp haproxy.pem root@hsnipe.moe:~
    networks:
      - proxy
      - default
    ports:
      - 80:80
      - 443:443

  grafana:
    << : *monitoring_defaults
    image: grafana/grafana:10.1.0
    container_name: grafana
    volumes:
      - /opt/grafana.ini:/etc/grafana/grafana.ini
      - /opt/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - /opt/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - /opt/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json

  prometheus:
    << : *monitoring_defaults
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    volumes:
      - /opt/prometheus.yml:/etc/prometheus/prometheus.yml

  cadvisor:
    << : *monitoring_defaults
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
      - '-storage_duration=2m0s'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    << : *monitoring_defaults
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave

  gitea:
    << : *application_defaults
    image: gitea/gitea:1.20.2
    container_name: gitea
    volumes:
      - /root/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  nginx:
    << : *application_defaults
    image: nginx:1.25.2-alpine
    container_name: nginx
    volumes:
      - /root/port19.xyz:/usr/share/nginx/html:ro

  syncplay:
    << : *application_defaults
    image: dnomd343/syncplay:v1.7.1
    container_name: syncplay
    networks:
      - proxy
    ports:
      - 8999:8999

  redqu:
    <<: *application_defaults
    image: ghcr.io/port19x/redqu:master
    container_name: redqu
    networks:
      - proxy
    volumes:
      - /root/secret.py:/secret.py
