scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["localhost:9113"]

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
