name: "continous awesomeness"
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  dominant_architecture:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: configure.yml
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [all]
            hsnipe.moe
            [all:vars]
            ansible_user=root
          requirements: requirements.yml
          options: |
            --verbose
