name: "continous awesomeness"
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  dominant_architecture:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          # Optional, SSH private key
          key: ${{secrets.SSH_KEY}}
          # Optional, SSH known hosts file content
          known_hosts: |
            rapturev2.example.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKKV2bIi3Ksj3lAksW1qBgBmTlM+c+auiY+A4aMq7KPr
          requirements: requirements.yml
          options: |
            --verbose
